window.FK_DATA = {
  "last_updated": "13 May 2026, 02:45 PM",
  "total": 15,
  "in_stock": 13,
  "oos": 0,
  "errors": 2,
  "results": [
    {
      "fsn": "MSCHBV8NDXMBG8ZY",
      "pin": "400059",
      "name": "",
      "price": null,
      "mrp": null,
      "disc": null,
      "in_stock": null,
      "seller": "",
      "rating": "",
      "error": "Page timeout",
      "ts": "13 May 26, 02:44 PM",
      "status": "error",
      "price_d": "",
      "mrp_d": "",
      "disc_d": ""
    },
    {
      "fsn": "MSCHBV8NDXMBG8ZY",
      "pin": "110001",
      "name": "Pilgrim Korean Rice Water Hydra Glow Moisturizer|Light Gel & Instant Glass Skin Glow",
      "price": 332.0,
      "mrp": null,
      "disc": null,
      "in_stock": true,
      "seller": "",
      "rating": "",
      "error": "",
      "ts": "13 May 26, 02:44 PM",
      "status": "in_stock",
      "price_d": "332",
      "mrp_d": "",
      "disc_d": ""
    },
    {
      "fsn": "MSCHBV8NDXMBG8ZY",
      "pin": "400001",
      "name": "Pilgrim Korean Rice Water Hydra Glow Moisturizer|Light Gel & Instant Glass Skin Glow",
      "price": 332.0,
      "mrp": null,
      "disc": null,
      "in_stock": true,
      "seller": "",
      "rating": "",
      "error": "",
      "ts": "13 May 26, 02:44 PM",
      "status": "in_stock",
      "price_d": "332",
      "mrp_d": "",
      "disc_d": ""
    },
    {
      "fsn": "FRNHFCJMEHZHHRQJ",
      "pin": "400059",
      "name": "",
      "price": null,
      "mrp": null,
      "disc": null,
      "in_stock": null,
      "seller": "",
      "rating": "",
      "error": "Page timeout",
      "ts": "13 May 26, 02:44 PM",
      "status": "error",
      "price_d": "",
      "mrp_d": "",
      "disc_d": ""
    },
    {
      "fsn": "FRNHFCJMEHZHHRQJ",
      "pin": "110001",
      "name": "Pilgrim 10% Vitamin C Face Serum for Oily Skin|Men & Women|Skin Brightening",
      "price": 510.0,
      "mrp": null,
      "disc": null,
      "in_stock": true,
      "seller": "",
      "rating": "",
      "error": "",
      "ts": "13 May 26, 02:44 PM",
      "status": "in_stock",
      "price_d": "510",
      "mrp_d": "",
      "disc_d": ""
    },
    {
      "fsn": "FRNHFCJMEHZHHRQJ",
      "pin": "400001",
      "name": "Pilgrim 10% Vitamin C Face Serum for Oily Skin|Men & Women|Skin Brightening",
      "price": 510.0,
      "mrp": null,
      "disc": null,
      "in_stock": true,
      "seller": "",
      "rating": "",
      "error": "",
      "ts": "13 May 26, 02:44 PM",
      "status": "in_stock",
      "price_d": "510",
      "mrp_d": "",
      "disc_d": ""
    },
    {
      "fsn": "SNRH89D3MFAMYNXU",
      "pin": "400059",
      "name": "Pilgrim Sunscreen - SPF 50+ PA++++ 5% Vitamin C Complex Brightening Serum Sunscreen, In-Vivo Tested ",
      "price": 360.0,
      "mrp": null,
      "disc": null,
      "in_stock": true,
      "seller": "",
      "rating": "",
      "error": "",
      "ts": "13 May 26, 02:44 PM",
      "status": "in_stock",
      "price_d": "360",
      "mrp_d": "",
      "disc_d": ""
    },
    {
      "fsn": "SNRH89D3MFAMYNXU",
      "pin": "110001",
      "name": "Pilgrim Sunscreen - SPF 50+ PA++++ 5% Vitamin C Complex Brightening Serum Sunscreen, In-Vivo Tested ",
      "price": 360.0,
      "mrp": null,
      "disc": null,
      "in_stock": true,
      "seller": "",
      "rating": "",
      "error": "",
      "ts": "13 May 26, 02:44 PM",
      "status": "in_stock",
      "price_d": "360",
      "mrp_d": "",
      "disc_d": ""
    },
    {
      "fsn": "SNRH89D3MFAMYNXU",
      "pin": "400001",
      "name": "Pilgrim Sunscreen - SPF 50+ PA++++ 5% Vitamin C Complex Brightening Serum Sunscreen, In-Vivo Tested ",
      "price": 360.0,
      "mrp": null,
      "disc": null,
      "in_stock": true,
      "seller": "",
      "rating": "",
      "error": "",
      "ts": "13 May 26, 02:44 PM",
      "status": "in_stock",
      "price_d": "360",
      "mrp_d": "",
      "disc_d": ""
    },
    {
      "fsn": "SMPHFCK9GNNGFXH7",
      "pin": "400059",
      "name": "Pilgrim Australian Tea Tree Hair Shampoo for Dandruff|Itchy Scalp|Men and Women",
      "price": 300.0,
      "mrp": null,
      "disc": null,
      "in_stock": true,
      "seller": "",
      "rating": "",
      "error": "",
      "ts": "13 May 26, 02:44 PM",
      "status": "in_stock",
      "price_d": "300",
      "mrp_d": "",
      "disc_d": ""
    },
    {
      "fsn": "SMPHFCK9GNNGFXH7",
      "pin": "110001",
      "name": "Pilgrim Australian Tea Tree Hair Shampoo for Dandruff|Itchy Scalp|Men and Women",
      "price": 300.0,
      "mrp": null,
      "disc": null,
      "in_stock": true,
      "seller": "",
      "rating": "",
      "error": "",
      "ts": "13 May 26, 02:44 PM",
      "status": "in_stock",
      "price_d": "300",
      "mrp_d": "",
      "disc_d": ""
    },
    {
      "fsn": "SMPHFCK9GNNGFXH7",
      "pin": "400001",
      "name": "Pilgrim Australian Tea Tree Hair Shampoo for Dandruff|Itchy Scalp|Men and Women",
      "price": 300.0,
      "mrp": null,
      "disc": null,
      "in_stock": true,
      "seller": "",
      "rating": "",
      "error": "",
      "ts": "13 May 26, 02:44 PM",
      "status": "in_stock",
      "price_d": "300",
      "mrp_d": "",
      "disc_d": ""
    },
    {
      "fsn": "FRNHFCJDBTSBZGNF",
      "pin": "400059",
      "name": "Pilgrim 10% Vitamin C Face Serum for Oily Skin|Men & Women|Skin Brightening",
      "price": 226.0,
      "mrp": null,
      "disc": null,
      "in_stock": true,
      "seller": "",
      "rating": "",
      "error": "",
      "ts": "13 May 26, 02:44 PM",
      "status": "in_stock",
      "price_d": "226",
      "mrp_d": "",
      "disc_d": ""
    },
    {
      "fsn": "FRNHFCJDBTSBZGNF",
      "pin": "110001",
      "name": "Pilgrim 10% Vitamin C Face Serum for Oily Skin|Men & Women|Skin Brightening",
      "price": 226.0,
      "mrp": null,
      "disc": null,
      "in_stock": true,
      "seller": "",
      "rating": "",
      "error": "",
      "ts": "13 May 26, 02:44 PM",
      "status": "in_stock",
      "price_d": "226",
      "mrp_d": "",
      "disc_d": ""
    },
    {
      "fsn": "FRNHFCJDBTSBZGNF",
      "pin": "400001",
      "name": "Pilgrim 10% Vitamin C Face Serum for Oily Skin|Men & Women|Skin Brightening",
      "price": 226.0,
      "mrp": null,
      "disc": null,
      "in_stock": true,
      "seller": "",
      "rating": "",
      "error": "",
      "ts": "13 May 26, 02:44 PM",
      "status": "in_stock",
      "price_d": "226",
      "mrp_d": "",
      "disc_d": ""
    }
  ]
};